---
title: "stats_plots"
output: html_document
---

```{r}
tropical = c('darkorange','dodgerblue','hotpink','limegreen','yellow')
palette(tropical)
par(pch=19)

library(gplots)
library(devtools)
library(Biobase)
library(RSkittleBrewer)
library(org.Hs.eg.db)
library(AnnotationDbi)
library(dplyr)

con = url("http://bowtie-bio.sourceforge.net/recount/ExpressionSets/bodymap_eset.RData")
load(file = con)
close(con)

bm = bodymap.eset
pdata = pData(bm)
edata = exprs(bm)
fdata = fData(bm)
```

edata
=====

check the 1st column of expression data
```{r}
boxplot(edata[,1])
```
check the data with log transformation
```{r}
boxplot(log2(edata[,1]+1))
```

filter outliner
```{r}
boxplot(log2(edata+1),col=2,range=0)
```

```{r}
hist(edata[,1],col=2,breaks=100) 
hist(log2(edata[,1]+1),breaks=100,col=2)
hist(log2(edata[,1]+1),col=2,breaks=100,xlim = c(1,15),ylim = c(0,400))
hist(rowSums(edata==0),col=2) # for each row, how many values == 0
low_genes = rowMeans(edata) < 5
table(low_genes)
filt_data = filter(as.data.frame(edata),!low_genes)
hist(log2(filt_data[,1]+1),breaks=100,col=2)
summary(edata)
low_genes = rowMedians(as.matrix(edata)) < 5
filt_data = filter(as.data.frame(edata),!low_genes)
hist(log2(filt_data[,1]+1),breaks=100,col=2)
```

```{r}
par(mfrow=c(1,1))
plot(density(log2(edata[,1]+1)),col=2)
lines(density(log2(edata[,2]+1)),col=3)
```

qq-plot
```{r}
qqplot(log2(edata[,1]+1),log2(edata[,2]+1),col=3)
abline(c(0,1)) # intercept and slope
```

MA-plot 
x:sum 
y:diff 
```{r}
mm = log2(edata[,1]+1) - log2(edata[,2]+1)
aa = log2(edata[,1]+1) + log2(edata[,2]+1)
plot(aa,mm,col=2)
```

```{r}
edata = as.data.frame(edata)
filt_data = filter(edata,rowMeans(edata)>1)
boxplot(as.matrix(log2(filt_data+1)),col=2)
```

fdata
=====
extract chromosome info
```{r}
aeid = as.character(fdata[,1])
aeid[1:5]
chr = AnnotationDbi::select(org.Hs.eg.db,keys=aeid,keytype="ENSEMBL",columns="CHR")
chr = chr[!duplicated(chr[,1]),]
all(chr[,1]==rownames(edata))
```

```{r}
edata = as.data.frame(edata)
edatay = dplyr::filter(edata,chr$CHR=="Y")
boxplot(colSums(edatay) ~ pdata$gender)
points(colSums(edatay) ~ jitter(as.numeric(pdata$gender)),
       col=as.numeric(pdata$gender),
       pch=19)
```

```{r}
ematrix = as.matrix(edata)[rowMeans(edata)>1000,]
heatmap(ematrix,Rowv = NA,Colv = NA)
```

